=== vcuaya/TecnologiasWeb/p11/serviciovod.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT CatalogoVOD (cuenta, contenido)>
<!ELEMENT cuenta (perfiles)>
<!ATTLIST cuenta correo CDATA #REQUIRED>
<!ELEMENT perfiles (perfil+)>
<!ELEMENT perfil (#PCDATA)>
<!ATTLIST perfil
    usuario ID #REQUIRED
    idioma (Spanish|English) #REQUIRED
>
<!ELEMENT contenido (peliculas, programas)>
<!ELEMENT peliculas (genero+)>
<!ELEMENT programas (genero+)>
<!ELEMENT genero (titulo+)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST genero nombre CDATA #REQUIRED>
<!ATTLIST titulo duracion CDATA #REQUIRED>

=== vcuaya/TecnologiasWeb/Base/serviciovod3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CatalogoVOD SYSTEM "serviciovod.dtd">
<CatalogoVOD>
    <cuenta correo="andres.manuel@presidencia.gob.mx">
        <perfiles>
            <perfil usuario="Andrés" idioma="Español" />
            <perfil usuario="Beatriz" idioma="Español" />
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas>
            <genero nombre="Super Héroes">
                <titulo duracion="2:37">ETERNALS</titulo>
                <titulo duracion="2:04">CAPITAN AMÉRICA, EL 1ER VENGADOR</titulo>
                <titulo duracion="0:00">&lt;video id="11">&amp;lt;&lt;/video></titulo>
            </genero>
            <genero nombre="Animadas">
                <titulo duracion="1:40">RED</titulo>
                <titulo duracion="1:47">RAYA</titulo>
                <titulo duracion="0:00">
                    <![CDATA[<video id="11">&lt;</video>]]>
                </titulo>
            </genero>
        </peliculas>
        <programas>
            <genero nombre="Comedia">
                <titulo duracion="0:30">FRIENDS</titulo>
                <titulo duracion="0:40">HOW I MEET YOUR MOTHER</titulo>
            </genero>
            <genero nombre="Suspenso">
                <titulo duracion="0:30">Stranger Things</titulo>
                <titulo duracion="0:45">Criminal Minds</titulo>
            </genero>
        </programas>
    </contenido>
</CatalogoVOD>

=== vcuaya/TecnologiasWeb/p11/serviciovod3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CatalogoVOD SYSTEM "serviciovod.dtd">
<CatalogoVOD>
    <cuenta correo="vcuaya@outlook.com">
        <perfiles>
            <perfil usuario="Sha" idioma="Spanish" />
            <perfil usuario="Diossue" idioma="Spanish" />
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas>
            <genero nombre="Drama">
                <titulo duracion="1h 42m">Casablanca</titulo>
                <titulo duracion="1h 59m">Citizen Kane</titulo>
                <titulo duracion="2h 12m">Parasite</titulo>
                <titulo duracion="2h 10m">&lt;video id="11">&amp;lt;&lt;/video></titulo>
            </genero>
            <genero nombre="Suspenso">
                <titulo duracion="1h 56m">Us</titulo>
                <titulo duracion="1h 44m">Get Out</titulo>
                <titulo duracion="1h 9m">The Cabinet of Dr. Caligari</titulo>
                <titulo duracion="1h 30m"><![CDATA[<video id="11">&lt;</video>]]></titulo>
            </genero>
        </peliculas>
        <programas>
            <genero nombre="Drama">
                <titulo duracion="0h 45m">Defending Jacob</titulo>
                <titulo duracion="0h 53m">Slow Horses</titulo>
                <titulo duracion="0h 49m">The Last Days of Ptolemy Grey</titulo>
                <titulo duracion="1h 3m">The Morning Show</titulo>
            </genero>
            <genero nombre="Suspenso">
                <titulo duracion="0h 57m">Severance</titulo>
                <titulo duracion="0h 50m">Tehran</titulo>
                <titulo duracion="0h 44m">Suspicion</titulo>
                <titulo duracion="0h 34m">Servant</titulo>
            </genero>
        </programas>
    </contenido>
</CatalogoVOD>
